// SPDX-License-Identifier: Apache-2.0
/* Copyright 2025 Spice Labs, Inc. \& Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. */

package io.spicelabs.ancho;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

/**
 * Tests for JFR event class generation.
 * Verifies the generated bytecode is valid and has the right structure.
 */
class EventClassGeneratorTest {

    @Test
    void generateEventClass_producesValidBytecode() {
        byte[] bytes = EventClassGenerator.generateEventClass(
                "io/spicelabs/ancho/events/spice_probe_test123",
                "spice.probe.test123",
                "TestClass testMethod");

        assertNotNull(bytes);
        assertTrue(bytes.length > 0);

        // Verify class file magic number (0xCAFEBABE)
        assertEquals((byte) 0xCA, bytes[0]);
        assertEquals((byte) 0xFE, bytes[1]);
        assertEquals((byte) 0xBA, bytes[2]);
        assertEquals((byte) 0xBE, bytes[3]);

        // Verify JDK 8 class version (52.0)
        // Major version is at bytes[6-7]
        int majorVersion = ((bytes[6] & 0xFF) << 8) | (bytes[7] & 0xFF);
        assertEquals(52, majorVersion, "Should target JDK 8 (class version 52)");
    }

    @Test
    void generateEventClass_containsEventName() {
        byte[] bytes = EventClassGenerator.generateEventClass(
                "io/spicelabs/ancho/events/spice_probe_abc",
                "spice.probe.abc",
                "My Label");

        // The event name should appear in the constant pool as a UTF8 string
        String bytesAsString = new String(bytes, java.nio.charset.StandardCharsets.ISO_8859_1);
        assertTrue(bytesAsString.contains("spice.probe.abc"),
                "Generated class should contain the event name");
        assertTrue(bytesAsString.contains("My Label"),
                "Generated class should contain the label");
    }

    @Test
    void generateEventClass_extendsJfrEvent() {
        byte[] bytes = EventClassGenerator.generateEventClass(
                "io/spicelabs/ancho/events/test_event",
                "spice.probe.test",
                "test");

        String bytesAsString = new String(bytes, java.nio.charset.StandardCharsets.ISO_8859_1);
        assertTrue(bytesAsString.contains("jdk/jfr/Event"),
                "Generated class should reference jdk.jfr.Event as superclass");
    }

    @Test
    void generateEventClass_uniquePerProbe() {
        byte[] bytes1 = EventClassGenerator.generateEventClass(
                "io/spicelabs/ancho/events/probe_aaa",
                "spice.probe.aaa", "Label A");
        byte[] bytes2 = EventClassGenerator.generateEventClass(
                "io/spicelabs/ancho/events/probe_bbb",
                "spice.probe.bbb", "Label B");

        // Same structure but different constant pool entries
        assertFalse(java.util.Arrays.equals(bytes1, bytes2),
                "Different probes should produce different bytecode");
    }

    @Test
    void eventPackageName() {
        assertEquals("io/spicelabs/ancho/events", EventClassGenerator.EVENT_PACKAGE);
    }

    @Test
    void probeEvent_hasClassGitoidField() throws Exception {
        byte[] bytes = EventClassGenerator.generateEventClass(
                "io/spicelabs/ancho/events/spice_probe_gitoid",
                "spice.probe.gitoid", "Gitoid Probe");
        Class<?> ev = new BytesClassLoader()
                .define("io.spicelabs.ancho.events.spice_probe_gitoid", bytes);

        assertTrue(jdk.jfr.Event.class.isAssignableFrom(ev));
        assertEquals(String.class,
                ev.getField(EventClassGenerator.PROBE_CLASS_GITOID_FIELD).getType(),
                "probe events must carry a String classGitoid field for ProbeAdvice to stamp");
        assertEquals(String.class,
                ev.getField(EventClassGenerator.PROBE_CALLER_GITOIDS_FIELD).getType(),
                "probe events must carry a String callerGitoids field");
    }

    @Test
    void classLoadedEvent_producesValidBytecodeWithFields() {
        byte[] bytes = EventClassGenerator.generateClassLoadedEvent();

        assertEquals((byte) 0xCA, bytes[0]);
        assertEquals((byte) 0xFE, bytes[1]);
        int majorVersion = ((bytes[6] & 0xFF) << 8) | (bytes[7] & 0xFF);
        assertEquals(52, majorVersion, "Should target JDK 8 (class version 52)");

        String asString = new String(bytes, java.nio.charset.StandardCharsets.ISO_8859_1);
        assertTrue(asString.contains("spice.ClassLoaded"), "Should carry the @Name value");
        assertTrue(asString.contains("jdk/jfr/Event"), "Should extend jdk.jfr.Event");
        for (String field : EventClassGenerator.CLASS_LOADED_FIELDS) {
            assertTrue(asString.contains(field), "Should declare field " + field);
        }
    }

    @Test
    void classLoadedEvent_loadsAsJfrEventSubclassWithAnnotations() throws Exception {
        byte[] bytes = EventClassGenerator.generateClassLoadedEvent();
        Class<?> ev = new BytesClassLoader().define(EventClassGenerator.CLASS_LOADED_FQN, bytes);

        assertTrue(jdk.jfr.Event.class.isAssignableFrom(ev),
                "Generated class must be a jdk.jfr.Event subclass");

        // All declared fields must be present and typed String.
        for (String field : EventClassGenerator.CLASS_LOADED_FIELDS) {
            assertEquals(String.class, ev.getField(field).getType(), field + " should be String");
        }

        assertEquals("spice.ClassLoaded", ev.getAnnotation(jdk.jfr.Name.class).value());
        assertTrue(ev.getAnnotation(jdk.jfr.Enabled.class).value(), "@Enabled should be true");
        assertFalse(ev.getAnnotation(jdk.jfr.StackTrace.class).value(), "@StackTrace should be false");
    }

    /** Minimal loader so we can define and reflect on the generated event class. */
    private static final class BytesClassLoader extends ClassLoader {
        BytesClassLoader() {
            super(EventClassGeneratorTest.class.getClassLoader());
        }

        Class<?> define(String fqn, byte[] bytes) {
            return defineClass(fqn, bytes, 0, bytes.length);
        }
    }
}
